version: "3.7"
services:
  postgres:
    image: postgres:alpine3.17
    restart: on-failure
    environment:
      POSTGRES_DB: "playlist"
      POSTGRES_USER: "go"
      POSTGRES_PASSWORD: "go"
      PGDATA: "/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
    
    